[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  base = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """
      default-src 'self' https://ayxltzvmpqxtyfvfotxd.supabase.co https://clientstream.launchdarkly.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://ayxltzvmpqxtyfvfotxd.supabase.co https://clientstream.launchdarkly.com;
      style-src 'self' 'unsafe-inline' https://rsms.me;
      img-src 'self' data: blob: https:;
      font-src 'self' data: https://rsms.me;
      connect-src 'self' https://ayxltzvmpqxtyfvfotxd.supabase.co wss://ayxltzvmpqxtyfvfotxd.supabase.co https://clientstream.launchdarkly.com wss://clientstream.launchdarkly.com;
      frame-src 'self';
      media-src 'self';
      object-src 'none';
      worker-src 'self' blob:;
      """
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Access-Control-Allow-Origin = "*"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  VITE_ENV = "production"
